ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ org.delcom.watchlist.ApplicationKt.module ]
    }
}
jwt {
    secret     = "change-me-in-production-use-long-random-string"
    secret     = ${?JWT_SECRET}
    issuer     = "watchlist-api"
    audience   = "watchlist-users"
    realm      = "WatchList API"
    expireDays = 7
    refreshExpireDays = 30
}
database {
    url      = "jdbc:postgresql://localhost:5432/watchlist"
    url      = ${?DATABASE_URL}
    user     = "postgres"
    user     = ${?DATABASE_USER}
    password = "postgres"
    password = ${?DATABASE_PASSWORD}
    driver   = "org.postgresql.Driver"
    maxPool  = 10
}
upload {
    dir = "uploads"
    dir = ${?UPLOAD_DIR}
    maxSizeMb = 5
}
